services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - auto-net
    #depends_on:
     # auto-redis:
      #  condition: service_healthy    
networks:
  auto-net:
    driver: bridge

